#   _____  .__                  ________  .__ __
#  /  _  \ |  |   ____ ___  ___ \______ \ |__|  | __ ___________
# /  /_\  \|  | _/ __ \\  \/  /  |    |  \|  |  |/ // __ \_  __ \
#/    |    \  |_\  ___/ >    <   |    `   \  |    <\  ___/|  | \/
#\____|__  /____/\___  >__/\_ \ /_______  /__|__|_ \\___  >__|
#        \/          \/      \/         \/        \/    \/
#
---
- hosts: localhost
  sudo: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

- hosts: localhost