# ALEX DIKER
# Network Automation

---
- name : Configure SNMP Contact
  hosts: "nexus_by_name"
  gather_facts: false
  connection: local

  vars:
    cli: "({ ansible_host })"
    username: "({ username })"
    password: "({ password })"
    transport: cli

  tasks:
    - name: configure snmp contact
      nxos_snmp_contact:
        contact: TEST_1
        state: present
        username: cisco123
        password: cisco123
        provider: "({ cli })"

      register: output

    - name: show output in output["end_state"]
      debug:
        msg: '{{ output["end_state]["contact"}}'

    - name: show output in output.end_state.contact
      debug:
        msg: '{{ output.end_state.contact }}'