---
# Automate Development Env Deployments.

- hosts: all

  roles:
  - common

- hosts: dbservers

  roles:
  - db

- hosts: devservers

  roles:
  - base-cisco
  - web

- hosts: lbservers

  roles:
  - haproxy

- hosts: monitoring

  roles:
  - base-cisco
  - nagios
