---
# Site Stack Example.

- hosts: all

  roles:
  - common

- hosts: dbservers

  roles:
  - db

- hosts: devservers

  roles:
  - base-apache
  - web

- hosts: lbservers

  roles:
  - haproxy

- hosts: monitoring

  roles:
  - base-apache
  - nagios