---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: 127.0.0.1
      username: alex
      password: alex
      name: vm_template
      validate_certs: True
      template: template_alex
      datacenter: DC002-90092-ALEX
      folder: /DC002-90092-ALEX/test/justasample/playbook/eyes
      state: poweredon
      wait_for_ip_address: yes